### ISSUE TITLE
Why --user?

### ISSUE THREAD

**Issue by InklingGirl** [essembeh/gnome-extensions-cli#2]
Is the `--user` switch required to properly install/use this app? Why is it the suggested method? Thank you.

**Comment by essembeh** [comment]
Hi

I tend to prefer installing 3rd party softwares (packages that are not validated by Debian) in the userland to avoid security issues as much as possible.
But if you trust enough a package you can install it for all your users, and you can install  `gnome-extensions-cli` for all users too.

The one setup you cannot do is installing  `gnome-extensions-cli` in a *virtualenv* that does not has access to system site packages, because of the way it uses some DBus python bindings (which were not available with pip) as far as I remember.

I hope I answered your question.

**Comment by SuggonM** [comment]
> The one setup you cannot do is installing gnome-extensions-cli in a virtualenv that does not has access to system site packages, because of the way it uses some DBus python bindings (which were not available with pip) as far as I remember.

Was just about to file an issue but I guess the virtualenv perfectly explains why extension manager was showing #35 after installing my extensions on a fresh system. Turns out the reason I didn't get an interactive prompt was because gext was silently falling back to `--filesystem` (due to virtualenv) which I had no idea about. Later when trying to use `--dbus`, I'd soon hit another issue #11.

@essembeh if possible, can a warning be added that would trigger if an ambiguous `gext install <ext>` is running inside a virtualenv? Or a warning to recommend against installing as virtualenv in the README?
