### ISSUE TITLE
Allow to disable colors (or automatically disable colors if stdout is not a tty)

### ISSUE THREAD

**Issue by felipecrs** [essembeh/gnome-extensions-cli#29]
I'm writing a script that uses `gext` to detect whether some extension is installed or not:

![image](https://github.com/essembeh/gnome-extensions-cli/assets/29582865/ba1e48b9-a06f-4c9c-b795-b59ca33bf3ca)

```console
gext list | grep --quiet "(arcmenu@arcmenu.com)"
```

But this doesn't work because gext's output is colorized and therefore grep doesn't match.

The workaround is https://stackoverflow.com/a/51141872:

```console
gext list | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' | grep --quiet "(arcmenu@arcmenu.com)"
```

But I believe this could be better handled by gext itself. For example, it could disable colors automatically when the stdout is not attached to a terminal (i.e. running in a pipeline).

**Comment by essembeh** [comment]
Hi

This is an excellent point.
When I tried to write an [alternative](https://github.com/essembeh/pytput) to [colorama](https://pypi.org/project/colorama/) I added an env variable to globally disable the colors and styles.

I choosed colorama over pytput to handle styles in this project, I did not think about this.

I'll develop a solution in gext since this is a totally valid point, idk if it will be an env var or an argument yet.

**Comment by essembeh** [comment]
After some research, there is no existing feature for now working with an env variable.

There was a [PR](https://github.com/tartley/colorama/pull/230) that was closed without merge.

But I think I'll go with the [solution proposed here](https://github.com/tartley/colorama/issues/268#issuecomment-973315094), kudos to thetasine.
