### ISSUE TITLE
Install fails when there is no graphical session

### ISSUE THREAD

**Issue by mrmeszaros** [essembeh/gnome-extensions-cli#3]
I wanted to configure a remote machine automatically and since there was no active session, the `dbus` backend failed.
Manually setting `--backend file` fixes the problem.

So I think the backend could gracefully fail-over to `file` if dbus is unavailable for some reason.
Most likely with a warning message.

**Comment by essembeh** [comment]
Hi

Sounds like a good idea!
I'll developp it soon. Thanks for the feedback

**Comment by essembeh** [comment]
Hi @mrmeszaros 

Your ticket gave me the motivation I needed to improve this project.
I just committed a *next* branch with some big improvement, but the CLI has changed a little, you might need to change some options.
The main changes are
- better lisibility with colors
- better performance for update
- dbus is the defaut backend, and filesystem is the fallback, unless you specify `--dbus` or `--filesystem`

I don't know if you are confortable with python enough to test it?
I did not publish a release on PyPI because I did not test it enough yet ...
And I need to update the documentation also :)

**Comment by mrmeszaros** [comment]
Hey, sorry for the long reply - had some other things to do.

I feel I have enough python knowledge to test it and review some code.

* For starters I see You chose `colorama` for terminal colors - why did You chose it?
I see it has not reached 1.0 yet on pypi, which is just a number, but still.
Here is a short list of alternatives, I will try to review them and see if there is an outstanding one ([r/Python link](https://www.reddit.com/r/Python/comments/svc78z/terminology_a_simpler_alternative_to_colorama/)).

* About the CLI change - I don't know how wide the userbase is, but usually I think a good practise is to add the new options while keeping old ones, with a deprecation message, like: _"Warning, this will be removed in version X.Y, use --ZZZ instead"_.

  However, since You have not reached 1.0 yet, not doing so should not be frowned upon.
Additionally, if the userbase is really small, deprecations might be an overkill.

  Also, I liked the `--backend [DBUS|FILE]` style option, it looked more professional that way.

* About the fallback mechanism - does this mean that explicitly passing `--dbus` disables the fallback mechanism? So, like:
    - (no option) - dbus, fallback to filesystem
    - --dbus - dbus, (no fallback)
    - --filesystem - filesystem, (no fallback)

I hope soon (by Sunday?) I can send you some feedback!

**Comment by essembeh** [comment]
Hi

Why colorama:
I've been using colorama a lot in the last 6 years on many projects, I'm used to it but I'll have a look to you link.

About cli change
I agree with you on that, CLI changes should be reflected with version updates.
I bumped the version to 0.9 because this tool is close to where I wanted it to be when I started it ... which should be the v1
And also because there were many changes with the previous version (like the `--dbus|--filesystem` as you noticed :) ).

`--dbus` vs `--backend XXX`
The first advantage is you only type on word :)
I would also like to rename `--filesystem` to something shorted and easier to understand.
And I didn't find the word *backend* meaningful here, for a CLI tool.

Fallback
Your right, I might need to update the doc to clarify this point

    (no option) - dbus, fallback to filesystem
    --dbus - dbus, (no fallback)
    --filesystem - filesystem, (no fallback)


Thanks for your feedbacks

**Comment by mrmeszaros** [comment]
Hey,

**On colorama:**
I did not like the alternatives, and their API was weird, did not offer anything extra.
I see now, it is widely used and under development, You are familiar with it, I think no need to change it.
Also, I found [colored](https://pypi.org/project/colored/). It's API seems to be a superset of colorama's.
Again, I changed my mind - no need to move from colorama.

**On CLI options:**
I agree, `--backend` does kind of lack meaning, and `--filesystem` feels clunky. I think if I (and the user) would understand what is the reason for having/chosing a different implementation, that would make it easier to chose a better wording for the two options.

So, AFAIK:
- using DBUS requires a graphical session, and by default opens a modal dialog to confirm installation intent. That can be overridden by `-y|--yes`.
- using FILE does not require a graphical session (and DBus), and asks to confirm the install in the command line - right? Also, it uses `subprocess` to run `gsettings` but also `dbus-send` (wait what? it also uses dbus?) to restart the GNOME shell changing the `enabled-extensions` list.

**On Fallback / updating the docs**
I think updating the doc should wait until the purpose of the two choices are clarified.
Currently in my mind the distinction is whether it needs active gnome shell session or not.

If that is the case that will simplify the issue of option naming and writing the documentation.

**Comment by essembeh** [comment]
First let me reopen this ticket to reflect the discussion.

For colorama, I tried to develop my own lib, based on tput: https://github.com/essembeh/pytput and I finally end up prefering colorama :) 

Concerning dbus:
- the graphical yes/no modal cannot be skipped, it is part of Gnome Shell (as a security?) to ensure no extension is installed in the background. 
- the `--yes` is just a confirmation *before* running updates, like apt. I'll soon add a `--no` which only prints updates, and do nothing, 
- the dbus interface I use is the same used in the official Firefox extension on Gnome website, so that I can guarantee that the extensions are installed the same way.

Concerning filesystem:
- installing the extension is nothing difficult, only unzip
- enabling an extensions relies on gsettings to add its uuid in a list, 
  - you don't need a graphical session to use gsettings
- but once enabled via gsettings, you have to *restart* Gnome Shell to actually run your newly enabled extensions
  - this process relies on dbus-send, but if it fails because you are using ssh, you only get a warning (pending commit i'm working on)

And last word, the dbus manager uses Python Dbus Library, unlike Filesystem manager which uses dbus with an external CLI tool.

**Comment by essembeh** [comment]
I close the ticket, you can reopen it if you need.

Thanks
