### ISSUE TITLE
update: --user flag ignored

### ISSUE THREAD

**Issue by eliminmax** [essembeh/gnome-extensions-cli#9]
I really appreciate how quickly you responded to issue reports last month, and I wish I'd gotten back sooner. The `--user` flag you added currently appears to be ignored, both in practice, and when looking at the code - it looks like it never checks `args.user` for anything.

**Comment by essembeh** [comment]
Hi

The feature was implemented in https://github.com/essembeh/gnome-extensions-cli/commit/9b72809d8d4612ce0bf525f55a719191175b9cfa
But I later removed it when refactoring the code https://github.com/essembeh/gnome-extensions-cli/commit/52e8047393bbf7dd36c6b2d75c40c299429ad16a

I'm sorry for that.


Also, I preferred the implementation in https://github.com/essembeh/gnome-extensions-cli/commit/a8da86a3f12ed88572bb8188c0bd019816c9a820 instead of the PR.

Thanks you
